myboard/common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path,include
from . import views

app_name = 'common'
urlpatterns = [
  path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
  path('logout/', auth_views.LogoutView.as_view(), name='logout'),
  path('signup/', views.signup, name='signup'),
]
# LoginView는 registration이라는 템플릿 디렉터리에서 login.html 파일을 찾는다
# registration/login.html 템플릿 파일을 작성하거나 따로 작성해서 연동

myboard/config/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
# from myapp.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    # path('', PostListView.as_view(), name='post-list'),
]

myboard/myapp/urls.py
from django.urls import path
# from .views import PostListView
from . import views

app_name = 'myapp'
urlpatterns = [
  path('', views.index, name='index'),
  # path('posts/', PostListView.as_view(), name='post-list'),
  path('<int:post_id>/', views.detail,name='detail'),
  path('post/create/', views.post_create,name='post_create'),
  path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
  path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
  path('comment/create/<int:post_id>/', views.comment_create,name='comment_create'),
  path('comment/modify/<int:comment_id>/', views.comment_modify,name='comment_modify'),
  path('comment/delete/<int:comment_id>/', views.comment_delete,name='comment_delete'),
  path('post/vote/<int:post_id>/', views.post_vote,name='post_vote'),
  path('comment/vote/<int:comment_id>/', views.comment_vote,name='comment_vote'),
  
  
]

myboard/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- myapp CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello!</title>
</head>
<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트  -->
{% block script %}
{% endblock %}
</body>
</html>

myboard/templates/form_errors.html
{% if form.errors %}
<div class="alert alert-danger py-1">
  {% for field in form %}
  <!-- 필드 오류 -->
  {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {% for error in field.errors %}
        <ul>
            <li style="list-style:none"> {{error}}</li>
        </ul>
        {% endfor %}
    </div>
  {% endif %}
  {% endfor %}
  <!-- 넌필드 오류: form수준에서 발생,중복 제출,clean_<fieldname>에서 유효성을충족시키지못할시 form.non_field_errors에 저장  -->
  {% for error in form.non_field_errors %}
  <div>
      <strong>{{ error }}</strong>
  </div>
  {% endfor %}
</div>
{% endif %}

myboard/templates/navbar.html
{%load static%}
<nav class="navbar navbar-expand-sm navbar-light bg-light border-bottom">
    <!--collapse : nav navbar-expand-sm이기때문에 상위태그에 맞춰 변동, button(navbar-toggler) or div(navbar-collapse) -->
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myapp:index' %}"><img src="{% static 'icons/home.png' %}" width="25px">MyBoard</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
                {% if user.is_authenticated %}
                <li class="nav-item" style="margin-right:10px">
                    <p><img src="{% static 'icons/person.png' %}" width="25px"><b>{{ user.username }}</b>님 반갑습니다</p>
                </li>
                <li class="nav-item" style="width:100px">
                    <a class="nav-link btn btn-dark" href="{% url 'common:logout' %}" > 로그아웃</a>
                </li>
                {% else %}
                <li>&nbsp;</li>
                <li class="nav-item btn">
                    <a class="nav-link btn btn-dark" href="{% url 'common:login' %}">로그인</a>
                </li>
                <li>&nbsp;</li>
                <li class="nav-item btn" >
                    <a class="nav-link btn btn-dark pl-3" href="{% url 'common:signup' %}">회원가입</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>