myboard/config/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
# from myapp.views import PostListView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
    # path('', PostListView.as_view(), name='post-list'),
]

myboard/myapp/urls.py
from django.urls import path
# from .views import PostListView
from . import views

app_name = 'myapp'
urlpatterns = [
  path('', views.index, name='index'),
  # path('posts/', PostListView.as_view(), name='post-list'),
  path('<int:post_id>/', views.detail,name='detail'),
  path('post/create/', views.post_create,name='post_create'),
  path('post/modify/<int:post_id>/', views.post_modify, name='post_modify'),
  path('post/delete/<int:post_id>/', views.post_delete, name='post_delete'),
  path('comment/create/<int:post_id>/', views.comment_create,name='comment_create'),
  path('comment/modify/<int:comment_id>/', views.comment_modify,name='comment_modify'),
  path('comment/delete/<int:comment_id>/', views.comment_delete,name='comment_delete'),
  path('post/vote/<int:post_id>/', views.post_vote,name='post_vote'),
  path('comment/vote/<int:comment_id>/', views.comment_vote,name='comment_vote'),
  
  
]

myboard/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_post')
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_post')
    def __str__(self):
        return self.title # 게시물의 제목을 문자열로 반환


# 댓글
class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')
    
    def __str__(self):
        return self.content
    
'''
역방향 참조(user와 연결된 필드가 1개일경우(author)) 
user = User.objects.get(id=특정_사용자의_ID)
posts_written_by_user = user.post_set.all()
user = User.objects.get(id=특정_사용자의_ID)
comments_written_by_user = user.comment_set.all()

related_name를 사용한 역방향참조
voter필드를 추가한후 user와 연결된 필드가 2개 user.모델명_set.all()로 가져오는데 이렇게 가져온내용이 author,voter의 구별이안되서 에러남
user = User.objects.get(id=특정_사용자의_ID)
posts_written_by_user = user.author_post.all()
user = User.objects.get(id=특정_사용자의_ID)
comments_written_by_user = user.author_comment.all()
'''

myboard/myapp/forms.py
from django import forms
from myapp.models import Post,Comment

class PostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ['title','content']
    # widgets = {
    #         'title': forms.TextInput(attrs={'class': 'form-control'}),
    #         'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
    #     }
    labels = {
            'title': '제목',
            'content': '내용',
        }  
class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ['content']
    labels = {
            'content': '댓글 내용',
        }      

myboard/myapp/views.py
from django.shortcuts import HttpResponse, render,get_object_or_404,redirect, resolve_url
from django.http import HttpResponseNotAllowed
from django.utils import timezone
from django.views.generic import ListView
from .models import Post,Comment
from .forms import PostForm,CommentForm
from django.core.paginator import Paginator 
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.


# class PostListView(ListView):
#     model = Post
#     template_name = 'myapp/post_list.html'
#     context_object_name = 'post_list'
#     ordering = ['-created_at']
#     paginate_by = 10

#     def get_queryset(self):
#         return Post.objects.order_by('-created_at') 

def index(request):
    page = request.GET.get('page', '1') 
    post_list = Post.objects.order_by('-created_at')
    paginator = Paginator(post_list, 10) #페이지당 10개씩
    page_obj = paginator.get_page(page)
    context = {'post_list':page_obj}
    return render(request,'myapp/post_list.html',context)

def detail(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    context = {'post':post}
    return render(request,'myapp/post_detail.html',context) 

'''
게시글 작성버튼을 누르면 get으로 request전달
form = PostForm()생성후, return render(request,'myapp/post_form.html',{'form':form})
post_form에서 form형식에맞는 내용작성 후 post로 request 재 전달(post_form의 form태그 action지정 안함,post_form.html은 create,modify등 form에해당하는 작업수행할 시에 공통으로 사용할 것이기 때문)
유효성검사이후 save(),redirect
'''
@login_required(login_url='common:login')
def post_create(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST) 
        if form.is_valid():
            post = form.save(commit=False) # 임시 저장
            post.author = request.user
            # post.created_at = timezone.now() --auto_now_add=True설정해서 괜찮을듯
            post.save() #저장
            return redirect('myapp:index')
    else:
        form = PostForm()    
    context ={'form':form}       
    #is_valid()가 폼 유효성 검사를 수행하고, 만약 폼이 유효하지 않은 경우 해당 폼 객체에 오류 메시지를 저장     
    return render(request,'myapp/post_form.html',{'form':form})

'''
게시글수정버튼 -> get으로 request전달 -> form = PostForm(instance=post) -> request와form을 myapp/post_form.html로 전달
post_form.html에서 post로 request 재 전달 -> PostForm(request.POST,instance=post) -> 유효성검사 -> save(),redirect
post_form.html form태그 action지정안함(view에 여러함수에서 재사용하려고)
'''
@login_required(login_url='common:login')
def post_modify(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    if request.user != post.author:
        messages.error(request,'수정권한이 없습니다.') #필드오류:입력값이 필드형식과불일치시/넌필드오류: 필드오류이외 발생.
        return redirect('myapp:detail',post_id=post.id)
    if request.method == "POST":
        form = PostForm(request.POST,instance=post) #해당인스턴스기준으로 생성하지만, request.POST로 덮어쓰기
        if form.is_valid():
            post = form.save(commit=False)
            post.updated_at = timezone.now() #수정시간
            post.save()
            return redirect('myapp:detail',post_id=post.id)
    else:
        form = PostForm(instance=post) 
    context = {'form':form}              
    return render(request,'myapp/post_form.html',context)

@login_required(login_url='common:login')
def post_delete(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    if request.user != post.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('myapp:detail', post_id=post.id)
    post.delete() #model에서 해당데이터객체 삭제 함수
    return redirect('myapp:index')

@login_required(login_url='common:login')
def comment_create(request,post_id):
    post = get_object_or_404(Post,pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post # 게시물 정보를 코멘트에 할당
            comment.author = request.user # author 속성에 로그인 계정 저장
            comment.save()
            # return redirect('myapp:detail',post_id=post.id)
            return redirect('{}#comment_{}'.format(resolve_url('myapp:detail',post_id=post.id),comment.id))
            #/myapp/detail/123#comment_4와같이 리다이렉트 :해시 프래그먼트 
    else:
        # @login_required(login_url='common:login')로 로그인페이지를 거쳐 해당 함수에 들어오면 get으로 접근하는거라 수정(input hidden타입, 다음로그인수행후 다음 url지정)
        # return HttpResponseNotAllowed('Only POST is possible.') #comment는 post로만 요청될것이기 때문에 오류발생시킴
        form = CommentForm()
    # post.comment_set.create(content=request.POST.get('content'))
    context = {'post':post,'form':form}
    return render(request,'myapp/post_detail.html',context)#form.is_valid()실패한경우 form에 에러메세지를 담아 리턴
    # comment = Comment(post=post,content=request.POST.get('content'))
    # comment.save()
    # return redirect('myapp:detail',post_id=post.id)

'''
comment수정을누르면 get으로 request전달
myapp/comment_form.html 에서 form작성후 post로 request 재전달(그래서 comment_form.html에서 form태그 action지정 안함 )
post로 전달된 request의 유효성체크 후 save(), redirect
'''    
@login_required(login_url='common:login')
def comment_modify(request,comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('myapp:detail', post_id=comment.post.id)
    if request.method =="POST":
        form = CommentForm(request.POST,instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.updated_at = timezone.now()
            comment.save()
            # return redirect('myapp:detail',post_id = comment.post.id)
            return redirect('{}#comment_{}'.format(resolve_url('myapp:detail',post_id=comment.post.id),comment.id))
    else:
        form = CommentForm(instance=comment)
    context = {'comment':comment,'form':form}
    return render(request,'myapp/comment_form.html',context)  
    
@login_required(login_url='common:login')
def comment_delete(request,comment_id):      
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        comment.delete()
    return redirect('myapp:detail',post_id=comment.post.id)  

@login_required(login_url='common:login')
def post_vote(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user == post.author:
        messages.error(request, '내가 작성한 글은 추천할 수 없습니다')
    else:
        post.voter.add(request.user)
    return redirect('myapp:detail', post_id=post.id)        

@login_required(login_url='common:login')
def comment_vote(request,comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user == comment.author:
        messages.error(request, '내가 작성한 글은 추천할 수 없습니다')
    else:
        comment.voter.add(request.user)
    return redirect('{}#comment_{}'.format(resolve_url('myapp:detail',post_id=comment.post.id),comment.id))        

myboard/templates/myapp/comment_form.html
{% extends 'base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

myboard/templates/myapp/post_detail.html
{% extends 'base.html' %}
{% load myapp_filter %}
{%load static%}
{% block content %}
<div class="container my-3">
<!-- post -->
    <!--post상단 수정&삭제 버튼-->
    <div class="my-3">
        <!-- message 표시(django.contrib import messages사용)
        1.(수정버튼이 작성자 == 로그인일때만 보이지만): 비정상적인 방법으로 질문수정 시도 시 2.본인추천  시 -->
        {% if messages %}
        <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
            <strong>{{ message.tags }}</strong>
            <ul><li style="list-style:none">{{ message.message }}</li></ul>
        {% endfor %}
        </div>
        {% endif %}
        <!-- 게시글 수정&삭제 (작성자 == 로그인) -->
        {% if request.user == post.author %}
        <div style="float:right">
        <a href="{% url 'myapp:post_modify' post.id  %}" 
        class="btn btn-sm btn-outline-secondary" style="padding-left:10px">수정<img src="{% static 'icons/pen.png' %}" width="25px"></a>
        <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary"
        data-uri="{% url 'myapp:post_delete' post.id  %}"style="padding-left:10px">삭제<img src="{% static 'icons/delete.png' %}" width="25px"></a>  
            <!-- javascript:void(0)해당링크를 눌러도 링크 동작안함 -->   
        </div>
        {% endif %}
    </div>

    <!--게시글제목-->
    <h2 class="border-bottom py-2">{{ post.title }}</h2>
    <!--게시글내용-->
    <div class="card my-3">
        <div class="card-body" style="height:500px; overflow: auto;position: relative;">           
            <div class="card-text">{{ post.content|mark }}</div>
            <div class="d-flex justify-content-end mb-3" style="position: absolute; bottom: 5px; right: 10px;">
                <!--추천버튼-->
                <a href="javascript:void(0)" data-uri="{% url 'myapp:post_vote' post.id  %}"
                class="recommend"> <img src="{% static 'icons/like.png' %}" width="25px">
                <span class="badge rounded-pill bg-danger">{{post.voter.count}}</span>
            </a>
                <!--post게시일자: 작성일자vs수정일자-->
                <div class="badge bg-light text-dark p-2">
                    {% if post.updated_at %}
                    (수정){{ post.updated_at|date:"y.m.d P" }}
                    {% else %}
                    {{ post.created_at|date:"y.m.d P" }}
                    {% endif %}
                </div>
            </div> 
        </div>        
    </div>
    
    <!-- comment -->
    <!--댓글갯수-->
    <h6 class="border-bottom my-3 py-2"><img src="{% static 'icons/comment.png' %}" width="20px">{{post.comment_set.count}}개의 댓글</h6>
    {% for comment in post.comment_set.all %}
    <!--작성&수정 시 해시프래그먼트포함해서 리다이렉트 -> 해당위치로이동 -->
    <a id="comment_{{ comment.id }}"></a>
    <!--댓글내용-->
    <div class="card my-2">
        <div class="card-body d-flex justify-content-between align-items-center pt-0 pb-1">
            <div class="card-text" >{{ comment.content|mark}}</div>
            <div>
                <div class="badge bg-light text-dark p-1 text-start">
                    <!--작성자-->
                    <div class="mb-2">{{ post.author.username }}</div>
                    <!--comment게시일자: 작성일자vs수정일자-->
                    <div>
                        {% if comment.updated_at %}
                        (수정){{ comment.updated_at|date:"y.m.d P" }}
                        {% else %}
                        {{ comment.created_at|date:"y.m.d P" }}
                        {% endif %}
                    </div>
                </div>
                <!--작성자 == 사용자 : 수정&삭제&추천-->
                <div>
                    <a href="javascript:void(0)" data-uri="{% url 'myapp:comment_vote' comment.id  %}"
                    class="recommend "> <img src="{% static 'icons/like2.png' %}" width="25px">
                    <span class="badge rounded-pill bg-secondary">{{comment.voter.count}}</span>
                    </a>
                    {% if request.user == comment.author %}
                    <a href="{% url 'myapp:comment_modify' comment.id  %}" 
                    class="btn btn-sm btn-outline-secondary"><img src="{% static 'icons/pen.png' %}" width="25px"></a>
                    <a href="#" class="delete btn btn-sm btn-outline-secondary "
                    data-uri="{% url 'myapp:comment_delete' comment.id  %}"><img src="{% static 'icons/delete.png' %}" width="25px"></a>
                    {% endif %}
                    
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 댓글 작성 -->
    <form action="{% url 'myapp:comment_create' post.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% include "form_errors.html" %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <!--로그인하지 않았을시 disabled-->
            <textarea {% if not user.is_authenticated %}disabled{% endif %} name="content" id="content" class="form-control" rows="1"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-dark">
    </form>
</div>
{% endblock %}

<!--삭제&추천 확인 박스 event-->
{% block script %}
<script type='text/javascript'>
    const delete_elements = document.getElementsByClassName("delete"); //class = 'delete'인 모든요소 가져오기
    Array.from(delete_elements).forEach(function(element) { // delete_elements의 array에서 forEach로 각각의 element에 동일한 eventListener할당
        element.addEventListener('click', function() {
            if(confirm("삭제하시겠습니까?")) {  //팝업된상자에서 선택에 따라 true,false
                location.href = this.dataset.uri; //요소의 dataset.uri 속성에 저장된 URL로 이동 (delete관련 view이동(또는 api 엔드포인트))
            };
        });
    });
    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    </script>
{% endblock %}

myboard/templates/myapp/post_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <!--오류를 form에 담은채로 다시 해당페이지를 랜더링 했을때 오류가없던 input에는 작성했던내용을 담은채로 보이도록 value설정-->
        <div class="mb-3">
            <label for="title" class="form-label">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                  value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-dark">저장하기</button>
    </form>
</div>
{% endblock %}
<!--
  form 태그에 action 속성을 지정하지 않으면 현재 페이지의 URL이 디폴트 action으로 설정 
<form method="post" action="{% url 'myapp:post_create' %}">
  -->

myboard/templates/myapp/post_list.html
{% extends 'base.html' %}
{%load static%}
{% load myapp_filter %}
{% block content %}
<div class="container my-3">
    <!--글작성버튼-->
    <div>
    <a href="{% url 'myapp:post_create' %}" class="btn btn-dark mb-3 mt-3 float-end"><img src="{% static 'icons/pen.png' %}" width="25px">&nbsp;작성</a>
    
    </div>
    <!--게시글 리스트-->
    <table class="table">
        <thead>
        <tr class="table-success text-center" style="border-top: 2px solid #000;">
            <th>번호</th>
            <th style="width:50%" >제목</th>
            <th>글쓴이</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if post_list %}
        {% for post in post_list %}
        <tr class="text-center">
            <!--게시글 넘버링:paginator를 사용해서 어려웠음 -->
            <!--|add-3처럼 필터는 인수로 숫자만되서 |sub필터를 직접만들어줌(sub:post_list.start_index 이렇게 적용하고싶어서)-->
            <!--myapp/templatetags/myapp_filter.py : templatetags폴더에서 사용자 정의 태그와 필터를 제공 규칙임-->
            <td>{{ post_list.paginator.count|sub:post_list.start_index|sub:forloop.counter0|add:1 }}</td>
            <td class="text-start">
                <a href="{% url 'myapp:detail' post.id %}">{{ post.title }}</a>
                <!--댓글갯수 표시-->
                {% if post.comment_set.count > 0 %}             
                <span class="text-danger small mx-2"><img src="{% static 'icons/comment.png' %}" width="15px">{{ post.comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ post.author.username }}</td>    
            <!--게시글생성 vs 수정 일자표시-->
            {% if post.updated_at %}
            <td style="font-size:0.8em">{{ post.updated_at|date:"y.m.d P" }}(수정)</td>
            {% else %}
            <td>{{ post.created_at|date:"y.m.d P" }}</td>
            {% endif %}                  
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">게시글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 : 처음,마지막버튼도 구현하기!!!!!!!!! -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if post_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ post_list.previous_page_number }}">&laquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&laquo;</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in post_list.paginator.page_range %}
        {% if page_number >= post_list.number|add:-5 and page_number <= post_list.number|add:5 %}
        {% if page_number == post_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if post_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ post_list.next_page_number }}">&raquo;</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">&raquo;</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    
</div>
{% endblock %}